select_category = "xpath://select[@id ='CategoryId']"
select_value_1="xpath://select[@id ='CategoryId']/option[@value ='1']"
txt_title = "xpath://textarea[@name='Title']"
txt_description="xpath://textarea[@id='Description']"
txt_environment="xpath://textarea[@id='txt_environment']"
iframe_txt_problem = "xpath://textarea[@id='txt_problem']/parent::div//iframe"
txt_problem ="xpath:/html/body/p"
txt_step_reproduce="xpath://textarea[@id ='txt_step_reproduce']"
txt_ErrorMessage ="xpath://textarea[@id ='txt_ErrorMessage']"
txt_workaround= "xpath://textarea[@id ='txt_workaround']"
iframe_txt_note ="xpath://textarea[@id='txt_note']/parent::div//iframe"
txt_note ="xpath:/html/body/p"
txt_tag ="xpath://input[@id ='txt_tags']"
txt_file="xpath://input[@type='file']"
btn_submit = "xpath://input[@name='submit']"


