btn_change = "xpath: //a[text() ='Chỉnh sửa']"
btn_change_email = "xpath://a[@id = 'email']"
btn_change_password = "xpath: //a[@id = 'change-password']"
txt_firstname_profile="xpath: //input[@id='Input_FirstName']"
txt_lastname_profile ="xpath: //input[@id='Input_LastName']"
txt_dob_profile = "xpath: //input[@id='Input_Dob']"
txt_phonenumber_profile ="xpath: //input[@id='Input_PhoneNumber']"
btn_change_account = "xpath: //button[@id = 'update-profile-button']"
txt_new_email = "xpath://input[@id = 'Input_NewEmail']"
btn_submit_change_email = "xpath://button[@id = 'change-email-button']"
alert_display_successfully = "xpath://div[@role = 'alert']"

txt_current_password = "xpath://input[@id = 'Input_OldPassword']"
txt_new_password = "xpath: //input[@id = 'Input_NewPassword']"
txt_confirm_new_password = "xpath: //input[@id = 'Input_ConfirmPassword']"
btn_update_password = "xpath: //button[text()= 'Cập nhật mật khẩu']"
